### ISSUE TITLE
ICSharpCode.AvalonEdit.dll still gets placed in the Dynamo 2.0 folder by the installer

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/BHoM_Installer#117]
#### Description:

As in the title - the .dll is responsible for breaking the Dynamo UI as explained by @adecler in https://github.com/BHoM/Dynamo_Toolkit/issues/289. I was trying to rule it out from Dynamo 2.0 in https://github.com/BHoM/Dynamo_Toolkit/pull/292, but apparently that only helps with build from source, while the issue still exists on the installer 😢

**Comment by FraserGreenroyd** [comment]
Please provide all the folder paths affected by the DLL so we can hunt it out when it comes down to looking into this.

**Comment by pawelbaran** [comment]
The following folders should not contain ICSharpCode.AvalonEdit.dll:
- %appdata%\Dynamo\Dynamo Revit\2.0\packages\BHoM\bin
- %appdata%\Dynamo\Dynamo Core\2.0\packages\BHoM\bin

**Comment by FraserGreenroyd** [comment]
See [this issue](https://github.com/BHoM/Grasshopper_Toolkit/issues/614) which will resolve the issue for the beta. This issue will then need revisiting once we bring back in the code editing functionality in a later milestone.
