### ISSUE TITLE
Error code 2349 

### ISSUE THREAD

**Issue by peterjamesnugent** [BHoM/BHoM_Installer#124]
#### Description:

Error code 2349 - BHoM Installer fails to complete.

#### Expected behaviour:

BHoM Installer to run successfully.

I have a feeling it is to do with admin rights as I cannot delete files from %ProgramData% - but confirmation of what the error code is would be useful.

**Comment by peterjamesnugent** [comment]
@FraserGreenroyd can confirm that this bug was caused by read/write permissions for the C:\ProgramData\BHoM folder. 

Happy for you to close it as it's no longer an issue - maybe add to the Wiki what the error code references and a potential solution.

**Comment by FraserGreenroyd** [comment]
Wiki page [here](https://github.com/BHoM/BHoM_Installer/wiki/Error-code-2349)
