### ISSUE TITLE
Remove existing Python environments upon running installer

### ISSUE THREAD

**Issue by tg359** [BHoM/BHoM_Installer#191]
#### Description:

Making sure that the Python environment associated with a code directory is of the same BHoM version is needed to stop disparity between them, and reduce the risk of things breaking! ~~If a difference is found the user should be notified and forced to install a new version of the environment before any code can be run.~~ Upon running an installer, where changes to the code have possibly been made, existing environments should be removed forcing the user to reinstall them. This means a very small change to Python_Toolkit, and the installer build process.

#### How to replicate:

Try running an older install of a downstream toolkit (such as LBT) after installing a newer version of BHoM to see that slight differences in code locations mean BHoM scripts built on those older versions no longer work.

#### Expected behaviour:

The installer process removes anything within the ProgramData/BHoM/Extensions/PythonEnvironments directory.

**Comment by FraserGreenroyd** [comment]
This will be picked up by the newest editions of the installer which will be coming in 2024, so rather than put resource into this I'm going to suggest we focus on the new version instead which can handle it for us 😄
