### ISSUE TITLE
Add CSharp_Toolkit to installer

### ISSUE THREAD

**Issue by al-fisher** [BHoM/BHoM_Installer#30]
#### Description:

Add the newly renamed and organised CSharp_Toolkit into the installer https://github.com/BHoM/CSharp_Toolkit

@FraserGreenroyd FYI

@adecler can you just confirm all happy and good to include this - ta

**Comment by FraserGreenroyd** [comment]
CSharp_Toolkit does not have any CI checks as yet, these would need adding prior to CSharp_Toolkit being included in an installer. I can get those set up tomorrow ready for inclusion.

**Comment by al-fisher** [comment]
Perfect! Thanks @FraserGreenroyd

**Comment by adecler** [comment]
@al-fisher, all happy and good

**Comment by FraserGreenroyd** [comment]
CI files and checks added to CSharp_Toolkit, awaiting review/approval/merging from @adecler or @al-fisher .

Once the PR is merged (https://github.com/BHoM/CSharp_Toolkit/pull/13) then this issue can be addressed as appropriate :smile:
