### ISSUE TITLE
Resolving unintuitive menu if reinstalling

### ISSUE THREAD

**Issue by al-fisher** [BHoM/BHoM_Installer#66]
Capturing conversations on installer menus here to then action.

With our installers being used in the wild for a while now, have had some anecdotal feedback that people are unsure which option to select on reinstall. 

![image](https://user-images.githubusercontent.com/15924573/84362980-f7a64f00-abc5-11ea-8fe9-0b2c27076494.png)

Agreed the following simplified options. _(here we might be departing from standard Windows wizard terminology - however I think, if we can be clear, that will be a better approach)_

#### Suggestion - Two Buttons only

- [ ] **"Reinstall"**
Select this option to simply reinstall this version of the BHoM on your machine.

- [ ]  **"Remove"**
This will uninstall BHoM completely from your machine, removing all plugins and BHoM toolkits.

This means excluding the "Change" option - as clicking **"Reinstall BHoM"** will basically ~take you through to the same Customise Dialogue you would get on initial install anyway~ do same as initial install. Thus just simplifying options to the above two.

**Comment by al-fisher** [comment]
On implementation - I have actually removed the Customise Dialogue entirely - this is something discussed before - and so adding it into this scope.

The BHoM is delivered as a package and thus (for now) think this is fine. 
Can revisit at later date.

@rwemay @FraserGreenroyd @adecler FYI

**Comment by rwemay** [comment]
All LGTM.
