### ISSUE TITLE
Add MachineLearning_Toolkit to the installer

### ISSUE THREAD

**Issue by epignatelli** [BHoM/BHoM_Installer#74]
#### Description:

As mentioned in https://github.com/BHoM/BHoM_Installer/issues/72, and after the fixes in https://github.com/BHoM/MachineLearning_Toolkit/pull/19, the MachineLearning_Toolki is ready to be included in the installer.

@FraserGreenroyd @MarthaVoul @tg359

**Comment by BingWangUS** [comment]
Wondering if we can include an option on the installer:
1. install python and machinelearning toolkits (maybe some ps script to call the current installPythonToolkit components?)
2. maintain previous installation (don't wipe previous installation, this is useful if the two toolkits did not change for daily alpha)
3. Don't include python and machinelearning toolkits (ie remove previous installation if exist)
