### ISSUE TITLE
Extensions folder should not be cleared

### ISSUE THREAD

**Issue by FraserGreenroyd** [BHoM/BHoM_Installer#88]
Following #77

And following #87 discussion

Extensions folder is staying but is cleared of files which is not the desired outcome. Needs investigating and fixing.

**Comment by pawelbaran** [comment]
Can we close this one @FraserGreenroyd?

**Comment by FraserGreenroyd** [comment]
I dunno, did we test this recently and find that it's resolved @pawelbaran ?

**Comment by pawelbaran** [comment]
Confirmed, the issue has been resolved.
